global using NUnit.Framework;
global using Domain.Abstractions;
global using Domain.Exceptions;
global using Domain.Models;
global using FakeItEasy;
global using System.Security.Claims;
global using System.Security.Principal;
global using Domain.Constants;
global using Microsoft.IdentityModel.JsonWebTokens;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Http.Internal;
global using Microsoft.Extensions.Hosting;
global using BCrypt.Net;
global using Microsoft.Extensions.Configuration;
global using System.IdentityModel.Tokens.Jwt;
global using ClaimNames = Microsoft.IdentityModel.JsonWebTokens.JwtRegisteredClaimNames;
