global using NUnit.Framework;
global using Domain.Exceptions;
global using Domain.Models;
global using FakeItEasy;
global using System.Security.Claims;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Http.Internal;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Configuration;
global using System.IdentityModel.Tokens.Jwt;
global using ClaimNames = Microsoft.IdentityModel.JsonWebTokens.JwtRegisteredClaimNames;
global using Services.Abstractions;
global using Services.Services;
global using Data.Abstractions;
